apiVersion: v1
kind: Service
metadata:
  name: {{ include "coolkit.fullname" . }}
  labels:
    {{- include "coolkit.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "coolkit.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.ports.http }}
    targetPort: http
    protocol: TCP
  - name: metrics
    port: {{ .Values.ports.metrics }}
    targetPort: metrics
    protocol: TCP
