apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coolkit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
  - repoURL: https://github.com/octaviobr/coolkit.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/octaviobr/coolkit.git
    targetRevision: main
    path: helm
    helm:
      valueFiles:
      - $values/argocd/values/coolkit-k3d-alpha.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - SkipDryRunOnMissingResource=true # CRDs may not exist on first sync
